@startuml
'https://plantuml.com/class-diagram

class Rasterizer {
    + draw()
}

class Game {
    + loop()
}

class Scene {
    - objects
}

class Player {
    + get_camera() -> Vector
    + react(event)
}

class Vector {
}

class Cube {
}

Game o--> Player : react
Game o--> Rasterizer : draw
Rasterizer o-> Player : get_camera
Rasterizer *--> Scene : рисует
Player *--> Scene : манипулирует
Scene *--> Cube : хранит

@enduml